### ISSUE TITLE
Display errors for all php-dev images

### ISSUE THREAD

**Issue by zaporylie** [drupal-docker/php#36]
`drupaldocker/php-dev` inherits settings from `drupaldocker/php`. Something like `error.ini` with overrides should be added.

Can we list here what we need?

```
error_reporting = E_ALL
display_errors = On
display_startup_errors = On
log_errors = On
ignore_repeated_errors = Off
ignore_repeated_source = Off
track_errors = On
```

File needs custom prefix (`x-error.ini`?) to be processed as the last one.

**Comment by slashrsm** [comment]
Makes sense. Can we make it use standard prefix that will be defined with #43?
