### ISSUE TITLE
Make all .ini files has common prefix

### ISSUE THREAD

**Issue by zaporylie** [drupal-docker/php#43]
I believe we should use common prefix for all Drupal customizations. That approach should reduce eventual php.ini negotiation problems.

Docker is already using `docker-php-ext-` so I think we can prepend all filenames with `drupal-` prefix. That should place our customizations after default docker settings for extensions.

**Comment by zaporylie** [comment]
If this goes in we can start using simplified syntax:

```
COPY drupal?.ini /usr/local/etc/php/conf.d/
```

**Comment by slashrsm** [comment]
Looks good to me. Standardization == nice.
