### ISSUE TITLE
Use alpine based images?

### ISSUE THREAD

**Issue by slashrsm** [drupal-docker/php#47]
Images based on alpine are way smaller than Debian based (~150M vs ~25M for official php images). 

Should we switch? Should we provide alpine based images along with debian based ones? I've been using alpine for solr and redis containers and I didn't notice any difference (besides file size).

**Comment by zaporylie** [comment]
There's only minor maintenance downside. Alpine does not have `apt-get` ;)

I have no problem with adding support for alpine-based images. I would actually prefer to just switch to alpine and drop debian based images. But we need yet-another-policy in order to do so.

**Comment by slashrsm** [comment]
We can close I guess?
