### ISSUE TITLE
Stop supporting 5.4 and 5.5

### ISSUE THREAD

**Issue by slashrsm** [drupal-docker/php#49]
Both are not supported any more. It would be safe to drop them in my opinion.

**Comment by zaporylie** [comment]
Agree. However I believe we should do it in an elegant way. Please read (and preferably comment on) #52. If you agree with 3 months notice we can terminate support for 5.4 and 5.5 by December ~13th.

**Comment by slashrsm** [comment]
Clearly a duplicate of #52.
