### ISSUE TITLE
Add deprecation policy

### ISSUE THREAD

**Issue by zaporylie** [drupal-docker/php#52]
Support for deprecated PHP versions should be terminated shortly after the branch reaches its end of life.

Proposition:
- Set deprecation date to 3 months from date it was announced but not earlier than branches' end of life.
- Add deprecation notice to versions table in README (and [drupal-docker/docs](/drupal-docker/docs))
- Support (feature & security) version until its deprecation date
- Do not remove deprecated version from Docker Registry - if project is build on top of deprecated version it will stop getting feature or security updates

**Comment by slashrsm** [comment]
Sounds good to me.

**Comment by zaporylie** [comment]
Added to docs.
