### ISSUE TITLE
drupaldocker/php-dev:7-cli does not exist

### ISSUE THREAD

**Issue by webflo** [drupal-docker/php#61]
https://hub.docker.com/r/drupaldocker/php-dev/ lists 7-cli as tag. But its not available and listed on https://hub.docker.com/r/drupaldocker/php-dev/tags/

**Comment by zaporylie** [comment]
Nice catch, thanks :) should be available in a couple of minutes.

**Comment by zaporylie** [comment]
It's available. Thanks again.
