### ISSUE TITLE
Include Drush or Console

### ISSUE THREAD

**Issue by iBobik** [drupal-docker/php#67]
For development of debugging on production is useful to have Drush or Drupal Console available in shell of PHP container. It is possible to add another container only with Drush or Console, but it is hard to use it with Docker Compose and deployment using it and this container will not have access to caches or files inside PHP container.

I propose to add tags drush or console to this image, so everybody can choose what fits better.

**Comment by iBobik** [comment]
Is PR welcome? Any strategic decision how it should be done?

**Comment by webflo** [comment]
I think the site/application should ship with console or drush. The site and the cli tool have to share the same autoloader anyway. I will only work for a short time.

**Comment by zaporylie** [comment]
I agree with @webflo on this one and that's something I've been promoting for long time now. https://github.com/drupal-docker/drush image is nice when you want to work directly on Drupal Core or Dockerize some legacy projects. 

For all new projects recommended setup is - https://github.com/drupal-composer/drupal-project - which comes with drush located in ./vendor/bin/drush by default (same with Console).

On the other hand I agree that we should add `mysql-client`, `openssh-client` and `rsync` packages to all PHP:CLI images we provide, to make it easy for end-users to use either Drush or Console. Right now those packages are installed in Drush Images which doesn't help if you use local Drush or Console.

**Comment by iBobik** [comment]
@zaporylie For a legacy projects on D7 i already has my own image what adds Drush and some other CLI tools to this image and this is the reason why I promote this.

For new projects I agree with shipping Console and Drush with the site.

**Comment by iBobik** [comment]
@zaporylie So how about to add mysql-client, openssh-client, rsync and composer? Currently I see drupaldocker/php:7.1-apache does not have it, so it can not be used for [drupal-composer/drupal-project](https://github.com/drupal-composer/drupal-project) by itself.

**Comment by zaporylie** [comment]
@iBobik Let's move this discussion to #70
